services:
  api:
    build: api
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    environment:
    - APP_PORT=0.0.0.0:3000
    - DB_ADDR=db:6379
    - DB_PASS=
    - DOMAIN=localhost:3000
    - API_QUOTA=10

  db:
    build: db
    ports: 
      - "6379:6379"
    volumes: 
      - .data:/data
