version: "3.8"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=0.0.0.0:3000
      - DB_ADDR=cunning-maggot-16287.upstash.io:6379
      - DB_PASS=default:AT-fAAIjcDExODQyOWM4MGIyMDg0NzBlOWU5OTVmZWQ5N2IxZWFjM3AxMA@cunning-maggot-16287.upstash.io:6379
      - DOMAIN=https://linkcut-1.onrender.com
      - API_QUOTA=10
